version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/smoothcrawler_cluster/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: requirements/requirements.txt
    - requirements: requirements/requirements-doc.txt
