name: smoothcrawler-cluster ci/cd
on:
  push:
    branches:
      - "develop"
      - "release"
      - "release-**"
      - "release/**"
      - "master"
    paths_ignore:
      - "docs/**"
      - "example/**"
      - ".gitcommitrules"
      - ".gitignore"
      - ".readthedocs.yaml"
      - "LICENSE"
      - "README.md"
  pull_request:
    branches:
      - "develop"
      - "release"
      - "release-**"
      - "release/**"
    paths_ignore:
      - "docs/**"
      - "example/**"
      - ".gitcommitrules"
      - ".gitignore"
      - ".readthedocs.yaml"
      - "LICENSE"
      - "README.md"

jobs:

  prep-testbed_unit-test:
#    name: Prepare all unit test items
    uses: Chisanan232/GitHub-Action-Template-Python/.github/workflows/prepare_test_items.yaml@master
    with:
      shell_path: scripts/ci/get-unit-test-paths.sh
      shell_arg: unix


  run_unit-test:
#    name: Run all unit test items
    needs: prep-testbed_unit-test
    uses: Chisanan232/GitHub-Action-Template-Python/.github/workflows/run_test_items_via_pytest.yaml@master
    with:
      test_type: unit-test
      all_test_items_paths: ${{needs.prep-testbed_unit-test.outputs.all_test_items}}


  unit-test_codecov:
#    name: Organize and generate the testing report and upload it to Codecov
    needs: run_unit-test
    uses: Chisanan232/GitHub-Action-Template-Python/.github/workflows/organize_and_generate_testing_report.yaml@master
    with:
      test_type: unit-test


  codecov_finish:
#    name: Organize and generate the testing report and upload it to Codecov
    if: github.ref_name == 'release' || github.ref_name == 'master'
    needs: [unit-test_codecov]
    uses: Chisanan232/GitHub-Action-Template-Python/.github/workflows/upload_test_report_to_codecov.yaml@master
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    with:
      download_path: ./
      codecov_flags: unittests
      codecov_name: smoothcrawler-cluster_github-actions_test # optional


  codacy_finish:
#    name: Upload test report to Codacy to analyse and record code quality
    needs: [unit-test_codecov]
    uses: Chisanan232/GitHub-Action-Template-Python/.github/workflows/upload_code_report_to_codacy.yaml@master
    secrets:
      codacy_token: ${{ secrets.CODACY_PROJECT_TOKEN }}
    with:
      download_path: ./


#  pre-building_check:
##    name: Check about it could work finely by installing the Python package with setup.py file
#    needs: [codecov_finish, codacy_finish]
#    uses: Chisanan232/GitHub-Action-Template-Python/.github/workflows/upload_code_report_to_codacy.yaml
#    with:
#      python_package_name: smoothcrawler
#      test_import_package_code_1: import smoothcrawler as mr
#      test_import_package_code_2: from smoothcrawler.crawler import SimpleCrawler
#      test_import_package_code_3: from smoothcrawler.components.data import BaseHTTPResponseParser, BaseDataHandler
#      test_python_script: ./scripts/test_crawler.py

