name: Test by 'develop'
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop


jobs:

  prep-testbed_unit-test:
#    name: Prepare all unit test items
    uses: ./.github/workflows/prepare_test_items.yaml
    with:
      shell_path: scripts/ci/get-unit-test-paths.sh
      shell_arg: unix


  run_unit-test:
#    name: Run all unit test items
    needs: prep-testbed_unit-test
    uses: ./.github/workflows/run_test_items_via_pytest.yaml
    with:
      test_type: unit-test
      all_test_items_paths: ${{needs.prep-testbed_unit-test.outputs.all_test_items}}


  unit-test_codecov:
#    name: Organize and generate the testing report and upload it to Codecov
    needs: [run_unit-test]
    uses: ./.github/workflows/organize_and_generate_testing_report.yaml
#    uses: ./.github/workflows/upload_test_report_to_codecov.yaml
#    secrets:
#      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    with:
      test_type: unit-test
#      codecov_flags: unittests
#      codecov_name: smoothcrawler-cluster_github-actions_test # optional


  codacy_finish:
#    name: Upload test report to Codacy to analyse and record code quality
    needs: [unit-test_codecov]
    uses: ./.github/workflows/upload_code_report_to_codacy.yaml
    secrets:
      codacy_token: ${{ secrets.CODACY_PROJECT_TOKEN }}
    with:
      download_path: ./

