name: Prepare test items

on:
  workflow_call:
    inputs:
      shell_path:
        required: true
        type: string
      shell_arg:
        required: true
        type: string
    outputs:
      all_test_items:
        description: "The first output string"
        value: ${{ jobs.prep-testbed_get_test_items.outputs.matrix }}


jobs:
  prep-testbed_get_test_items:
    name: Prepare all test items
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      matrix: ${{ steps.set-matrix.outputs.all_test_items }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          sudo apt-get install jq
          echo "$(bash ${{ inputs.shell_path }} ${{ inputs.shell_arg }})"

