name: smoothcrawler-cluster tox test

on:
  push:
    branches:
      - "develop"
      - "release"
      - "release-**"
      - "release/**"
      - "master"
    paths:
      - ".github/workflows/tox-test.yaml"
      - "tox.ini"

  pull_request:
    branches:
      - "develop"
      - "release"
      - "release-**"
      - "release/**"
      - "master"
    paths:
      - ".github/workflows/tox-test.yaml"
      - "tox.ini"

jobs:
  test-tox:
#    name: Test the tox.init is valid, and ensure that it could run finely.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install the Python dependencies
        run: pip3 install -r ./requirements/requirements-test.txt

      - name: Test to run Tox command
        run: tox -- unit-test

