name: Upload code detail report to Codacy

on:
  workflow_call:
    inputs:
      download_path:
        required: true
        type: string

    secrets:
      codacy_token:
        required: true


jobs:
  upload_code_to_codacy_check_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Download testing coverage report
        uses: actions/download-artifact@v3
        with:
          name: project_coverage_report
#          path: ./coverage.xml
          path: ${{ inputs.download_path }}

      - name: Generate testing report for Codacy
        run: mv ./coverage.xml ./cobertura.xml

      - name: Upload testing report to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.codacy_token }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: cobertura.xml

